### ISSUE TITLE
Wie bekommt man eine publisher ttl?

### ISSUE THREAD

**Issue by giannou** [LOD-GEOSS/databus-snippets#1]
Frage von @christian-rli

**Comment by yum-yab** [comment]
So eine webID kann man mithilfe der beschreibung [dieses repos](https://github.com/dbpedia/webid) generieren (es gibt auch ein script das man einfach ausführen kann). Ich habe mal beispielhaft eine [lod-geoss webid](https://github.com/LOD-GEOSS/databus-snippets/blob/master/webid/webid.ttl) erstellt für den neuen [lod-geoss account](https://databus.dbpedia.org/lod-geoss).

Sobald man das gemacht hat muss man das noch registrieren, das passiert aktuell manuell, dazu einfach @yum-yab oder @JJ-Author ansprechen.

Aber das wird in Zukunft alles gar nicht mehr nötig sein, da diese Arbeit der databus für einen übernimmt, also weiß ich nicht ob es sich noch lohnt so eine webid zu erstellen.
