### ISSUE TITLE
Missing documentation for variables necessary for registration

### ISSUE THREAD

**Issue by giannou** [LOD-GEOSS/databus-snippets#2]
If there is an existing documentation for databus variables, please provide the link here. We should insert this into the readme with a detailed description of what is needed for a registration.

Issue opened by @christian-rli

**Comment by yum-yab** [comment]
In the [README of this repository](https://github.com/LOD-GEOSS/databus-snippets#step-1-generating-the-dataid) is now a table with the needed parameters for the DataID upload. Since the the development of the dataid/API is still ongoing I'll try to keep it updated if something gets added/deleted

**Comment by giannou** [comment]
Thanks for putting together the table, very useful!
