### ISSUE TITLE
unable to perform query suggested by dev.databus.dbpedia.org

### ISSUE THREAD

**Issue by giannou** [LOD-GEOSS/databus-snippets#6]
Running the query found on this page works:
https://databus.dbpedia.org/lod-geoss/KSz_2050/KS95_emissions/

But the query from this one doesn't:
https://dev.databus.dbpedia.org/denis/general/testartifact/

Is the dev.databus not ready to accept queries yet?

**Comment by yum-yab** [comment]
Here it is important to select the correct SPARQL endpoint (in the top row of most web SPARQL endpoints you can select your target repo URI) to send the query to, in the case of dev.databus it is https://dev.databus.dbpedia.org/system/sparql. [Here](https://yasgui.triply.cc/#query=PREFIX%20dataid%3A%20%3Chttp%3A%2F%2Fdataid.dbpedia.org%2Fns%2Fcore%23%3E%0APREFIX%20dct%3A%20%20%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20dcat%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20db%3A%20%20%20%20%20%3Chttps%3A%2F%2Fdatabus.dbpedia.org%2F%3E%0APREFIX%20rdf%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20rdfs%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0ASELECT%20DISTINCT%20%3Ffile%20WHERE%20%7B%0A%09GRAPH%20%3Fg%20%7B%0A%09%09%3Fdataset%20dcat%3Adistribution%20%3Fdistribution%20.%0A%09%09%3Fdistribution%20dataid%3Afile%20%3Ffile%20.%0A%09%09%3Fdataset%20dataid%3Aartifact%20%3Chttps%3A%2F%2Fdev.databus.dbpedia.org%2Fdenis%2Fgeneral%2Ftestartifact%3E%20.%0A%09%09%7B%0A%09%09%09%3Fdistribution%20dct%3AhasVersion%20%3Fversion%20%7B%0A%09%09%09%09SELECT%20(%3Fv%20as%20%3Fversion)%20%7B%20%0A%09%09%09%09%09%3Fdataset%20dataid%3Aartifact%20%3Chttps%3A%2F%2Fdev.databus.dbpedia.org%2Fdenis%2Fgeneral%2Ftestartifact%3E%20.%20%0A%09%09%09%09%09%3Fdataset%20dct%3AhasVersion%20%3Fv%20.%20%0A%09%09%09%09%7D%20ORDER%20BY%20DESC%20(%3Fversion)%20LIMIT%201%20%0A%09%09%09%7D%0A%09%09%7D%0A%09%7D%0A%7D&endpoint=https%3A%2F%2Fdev.databus.dbpedia.org%2Fsystem%2Fsparql&requestMethod=POST&tabTitle=Query%202&headers=%7B%7D&contentTypeConstruct=application%2Fn-triples%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table) you can see an example query at triplys yasgui.

**Comment by giannou** [comment]
Perfect, thanks!
