### ISSUE TITLE
argument `user` ignored?

### ISSUE THREAD

**Issue by giannou** [LOD-GEOSS/databus-snippets#7]
What is the purpose of the `user` argument in this function?
https://github.com/LOD-GEOSS/databus-snippets/blob/91bc01f1695e7d8040e895ce99e022dee9ca8146/dev_databus_api_example.py#L207

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Should replace the hard-coded "denis", no?
https://github.com/LOD-GEOSS/databus-snippets/blob/91bc01f1695e7d8040e895ce99e022dee9ca8146/dev_databus_api_example.py#L233-L234

**Comment by giannou** [comment]
doesn't the function `deploy_to_dev_databus` definition end at line 218?

**Comment by yum-yab** [comment]
Hi Guys, sorry for the confusion.
@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q is right, this is a useless parameter from copying the method. I fixed it in the new [commit](https://github.com/LOD-GEOSS/databus-snippets/commit/9b2d61ef2e787141be8811d2c86411162873f1a9). 
The user is still needed bit is encoded in the objects (`DataVersion`,`DataGroup`) with the variable `account_name` (which should be set to your dev databus account name).

**Comment by giannou** [comment]
awesome thanks
