### ISSUE TITLE
python script for deployment to dev databus not working any more

### ISSUE THREAD

**Issue by giannou** [LOD-GEOSS/databus-snippets#9]
The python code for deploying to the dev databus does not work. 

Not sure if it's worth fixing as the dev databus seems to be [pretty unstable now](https://github.com/dbpedia/databus/issues/12) anyway.

The question is rather which databus will the LOD-GEOSS project be using? If it's the dev databus then we need to discuss how to proceed.

**Comment by giannou** [comment]
Update:

Thanks @JJ-Author for putting together the energy.databus.dbpedia.org. After creating a profile there and changing the paths in the python code of @yum-yab to point to the new URI, the API still doesn't work. The output is around 1000 lines long so not much sense to copy it here. Any idea how to fix this?

**Comment by JJ-Author** [comment]
@yum-yab is on vacation until wednesday. then he will take care of it. please post the error anyhow.

**Comment by giannou** [comment]
[output.txt](https://github.com/LOD-GEOSS/databus-snippets/files/8213247/output.txt)

Thanks, here's the output of `python3 dev_databus_api_example.py`

**Comment by yum-yab** [comment]
Since I updated the script several times since then and it works now, I'll close this issue.

Also the error was on the databus site, not the script.
